// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Horca {
	protected static final int MAX_FALLOS = 6;
	/**
	 * 
	 */
	private int fallo;

	public int getFallos(){
		return this.fallo;
	}
	
	/**
	 * 
	 */
	public void dibujar() {
	}

	/**
	 * 
	 */
	public void incrementarFallo() {
		fallo++;
	}

	/**
	 * 
	 */
	public boolean comprobarSiPerdido() {
		return (fallo == MAX_FALLOS);
	}
	
	
};
