// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Palabra {
	/**
	 * 
	 */
	private String palabraOculta;
	/**
	 * 
	 */
	private char[] letrasDescubiertas;
	/**
	 * 
	 */
	private char[] letrasFallidas;

	/**
	 * 
	 */
	public String elegirPalabra() {
		String[] palabras = {"jirafa", "perro", "gato", "gallo", "elefante", "rata", "tortuga"};
		
		String elegida = palabras[(int) (Math.random() * (palabras.length-1))];
		
		
		return elegida;
	}

	/**
	 * 
	 * @return  
	 */
	public boolean comprobarLetra(char letra) {
		if (palabraOculta.indexOf(letra) == -1) 
			return false; 
				else return true;
		
		
	}

	/**
	 * 
	 */
	public void mostrarResultados() {
	}

	/**
	 * 
	 * @return  
	 */
	public boolean comprobarSiGanado() {
	}

	/**
	 * 
	 * @return  
	 */
	public String comprobarPalabra() {
	}
};
