// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------



package Ahorcado;



import java.util.*;

import java.lang.Character;


/**
 * Esta es la clase principal del juego. En ella se almacenan los datos sobre la partida que se esté jugando, así mismo,
 * también contabiliza la cantidad de puntos del jugador.
 * 
 * @author ionoproxy
 */

public class Partida {

	/**
	 * Variable que contiene el nombre del jugador.
	 */

	private static String nombreJugador;

	/**
	 *  Variable que crea un nuevo juego de Horca.
	 */

	public static Horca horca;

	/**
	 * Variable que se empleará para crear una palabra secreta y basar el juego en ella.
	 */

	public static Palabra palabra;


	/**
	 * Función que cuenta el puntaje de la partida.
	 */

	public void contadorPuntos() {

	}



	/**
	 * Muestra el progreso de la horca, y el resultado de la palabra que vaya obteniendo el jugador.
	 */

	public static void mostrarProgreso() {
		horca.dibujar();
		palabra.mostrarResultados();
	}



	/**
	 * Función que pide al jugador una letra a adivinar.
	 * 
	 * @return Devuelve la letra que será insertada en alguno de los array, según sea correcta o no.
	 */

	public static char pedirLetra() {

		Scanner input = new Scanner(System.in);

		System.out.print("Introduce una letra a adivinar: ");

		char letra = input.nextLine().charAt(0);



		return Character.toLowerCase(letra);

	}



	/**
	 * Función que pregunta al jugador la palabra para resolver el juego.
	 * 
	 * @return Devuelve true en caso de que el jugador haya acertado la palabra,
	 * 		   devuelve false en caso de que el jugador no haya acertado la palabra.
	 */

	public static boolean resolver() {

		Scanner entrada = new Scanner(System.in);

		System.out.print("Introduce la palabra: ");

		return palabra.comprobarPalabra(entrada.nextLine().toLowerCase());

	}



	/**
	 * Función que comprueba si hemos agotado las oportunidades o si hemos acertado todas las letras.
	 * 
	 * @return Devuelve true tanto si hemos ganado como perdido, devuelve false si todavía el jugador puede jugar.
	 */

	public static boolean comprobarFinal() {

		return horca.comprobarSiPerdido() || palabra.comprobarSiGanado();

	}



	/**
	 * Función que muestra el menú principal del juego, con el cual el jugador podrá interactuar en la partida.
	 * 
	 * @return Devuelve el valor del menú seleccionado.
	 */

	public static int elegirDelMenu() {

		Scanner input = new Scanner(System.in);

		System.out.println("\n*--------------------------------*");
		System.out.println("Elige una opción para jugar: \n");
		System.out.println("1. Quiero escribir una letra");
		System.out.println("2. ¡Quiero resolver!");
		System.out.println("3. Abandonar");
		System.out.println("*--------------------------------*");

		return input.nextInt();

	}



	public static void main(String[] args) {

		Scanner input = new Scanner(System.in);

		System.out.println("¿Cuál es tu nombre, valiente?");

		System.out.print("Mi nombre es... ");

		nombreJugador = input.nextLine();


		horca = new Horca();

		palabra = new Palabra();

		boolean noHaResueltoMal = true;

		System.out.println("\n\nBIEVENIDO AL AHORCADO DE IES SON FERRER");
		System.out.println("=======================================");

		
		palabra.elegirPalabra();


		while (!comprobarFinal() && noHaResueltoMal) {

			switch (elegirDelMenu()) {

			case 1:
				palabra.comprobarLetra(pedirLetra());
				mostrarProgreso();
				break;

			case 2:
				if (resolver()) {
					System.out.println("=============");
					System.out.println("¡Has ganado, " + nombreJugador + "!");
					System.out.println("=============");

					noHaResueltoMal = false;
				} else {
					System.out.println("Lo siento, has perdido...");
					noHaResueltoMal = false;
				}

				break;

			case 3:
				System.out.println("¡Eres un cobarde, " + nombreJugador + "!");
				System.exit(0);

			default:
				break;

			}

		}



	}



}